# https://travis-ci.org/alexpirine/shelf-cms
language: python
python:
    - "2.7"
    - "pypy"
install:
    - pip install --upgrade pip
    - pip --version
    - python setup.py install
script:
    - python setup.py sdist
