# https://travis-ci.org/alexpirine/shelf-cms
sudo: false
language: python
python:
  - "2.7"
install:
  - make install
script:
  - make test
after_failure:
  - pip install imgurpython
  - python tests/upload_failure_screens.py
after_success:
  - pip install codecov
  - codecov
git:
  depth: 10
