# https://travis-ci.org/alexpirine/shelf-cms
language: python
python:
    - "2.7"
install:
    - pip install -r requirements-dev.txt
    - python setup.py install
script:
    - python setup.py sdist
    - make test
