# https://travis-ci.org/alexpirine/shelf-cms
sudo: false
language: python
python:
  - "2.7"
install:
  - make install
script:
  - make test
  - make requirements
  - make sdist
before_install:
  - pip install codecov
after_success:
  - codecov
